#!/usr/bin/env bash
# script to install nginx and configure redirect and error page 404

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello world!" | sudo tee /var/www/html/index.html
page_red="\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/eberechi10"
sudo sed -i "37i\ $page_red" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
404_page="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "37i\ $404_page" /etc/nginx/sites-available/default
sudo service nginx stop
sudo service nginx start
