#!/usr/bin/env bash
# configures Nginx to use HTTP response custom header

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo bash -c 'cat <<EOL > /etc/nginx/sites-enabled/default
server {
    listen 80;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/html;
    index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/eberechi10;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}
EOL'

if ! grep -q 'add_header X-Served-By \$hostname;' /etc/nginx/sites-enabled/default; then
    sudo sed -i '/^http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites_enabled/default
fi

sudo service nginx restart
