#!/usr/bin/env bash
# script modify Nginx server to listen port 80 and  kills the nginx process
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
