#!/usr/bin/env bash
# script to display "Best School" 10 times but displays Hi in 9th using a while loop and if 
x=0
while [ $n -lt 10 ]
do
    echo "Best School"
    x=$(( x + 1 ))

    if [ $x == 9 ]
    then
        echo "Hi"
    fi
done
