#!/usr/bin/env bash
# script to displays numbers from 1 to 20.

x=1
while [ $x -le 20 ]
do
  echo "$x"
  case $x in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( x++ ))
done
