#!/usr/bin/env bash
# script to display information about the file call school`
node="school"

if [ -e "node" ]
then
  echo "node file exists"
  if [ -s "node" ]
  then
    echo "node file is not empty"
  else
    echo "node file is empty"
  fi

  if [ -f "node" ]
  then
    echo "node is a regular file"
  fi
else
  echo "node file does not exist"
fi
