#!/usr/bin/env bash
# script resolv local IP address of Facebook and localhost.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2     localhost" > ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
